codecov:
  token: ${CODECOV_TOKEN}
  require_ci_to_pass: yes
  notify:
    after_n_builds: 1

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        # Overall project coverage target (tightened)
        target: 90%
        threshold: 1%
        informational: false
        flags:
          - unittests
        paths:
          - src/newyearscards
    patch:
      default:
        # Require high coverage on changed lines (tightened)
        target: 95%
        threshold: 1%
        informational: false

flags:
  unittests:
    carryforward: true
    paths:
      - src/newyearscards

ignore:
  - tests/
  - docs/
  - keys/
  - data/
  - templates/
  - newyearscards

comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false

github_checks:
  annotations: true
